[package]
name = "MonJeuSui"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
# C'est cette ligne qui corrige l'erreur sur "struct" (en important SUI)
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
# C'est cette ligne qui corrige l'erreur sur "game"
game = "0x0"
suppression front + debut test sur suitestnet