[package]
name = "eggs_game"
version = "0.0.1"
edition = "2024.beta"
# license = ""
# authors = ["..."]

[dependencies]
# Required to bring Sui framework modules (resolves struct import issues)
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
eggs_game = "0x0"
chimera = "0x0"
game = "0x0" # used by monster_* and currency modules

[dev-dependencies]
# Example: Local = { local = "../path/to/dev-build" }

[dev-addresses]
# Example override for tests: alice = "0xB0B"

# suppression front + debut test sur suitestnet
